# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
      - 'release/*.*.*'
  pull_request:
    branches:
      - master
      - 'release/*.*.*'

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 8 ]
        distro: [ 'zulu', 'temurin' ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }} ${{ matrix.distro }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.distro }}
    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip=true
    - name: Unit Test
      run: mvn cobertura:cobertura -Dmaven.test.skip=false -Dtest=**/value/**/**.java
    - name: Upload
      run: bash <(curl -s https://codecov.io/bash)
